// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: sourcenetwork/sourcehub/acp/tx.proto

package types

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on MsgCreatePolicy with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *MsgCreatePolicy) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MsgCreatePolicy with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MsgCreatePolicyMultiError, or nil if none found.
func (m *MsgCreatePolicy) ValidateAll() error {
	return m.validate(true)
}

func (m *MsgCreatePolicy) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Creator

	// no validation rules for Policy

	// no validation rules for MarshalType

	if all {
		switch v := interface{}(m.GetCreationTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MsgCreatePolicyValidationError{
					field:  "CreationTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MsgCreatePolicyValidationError{
					field:  "CreationTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreationTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MsgCreatePolicyValidationError{
				field:  "CreationTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MsgCreatePolicyMultiError(errors)
	}

	return nil
}

// MsgCreatePolicyMultiError is an error wrapping multiple validation errors
// returned by MsgCreatePolicy.ValidateAll() if the designated constraints
// aren't met.
type MsgCreatePolicyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MsgCreatePolicyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MsgCreatePolicyMultiError) AllErrors() []error { return m }

// MsgCreatePolicyValidationError is the validation error returned by
// MsgCreatePolicy.Validate if the designated constraints aren't met.
type MsgCreatePolicyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MsgCreatePolicyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MsgCreatePolicyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MsgCreatePolicyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MsgCreatePolicyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MsgCreatePolicyValidationError) ErrorName() string { return "MsgCreatePolicyValidationError" }

// Error satisfies the builtin error interface
func (e MsgCreatePolicyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMsgCreatePolicy.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MsgCreatePolicyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MsgCreatePolicyValidationError{}

// Validate checks the field values on MsgCreatePolicyResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MsgCreatePolicyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MsgCreatePolicyResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MsgCreatePolicyResponseMultiError, or nil if none found.
func (m *MsgCreatePolicyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MsgCreatePolicyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPolicy()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MsgCreatePolicyResponseValidationError{
					field:  "Policy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MsgCreatePolicyResponseValidationError{
					field:  "Policy",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPolicy()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MsgCreatePolicyResponseValidationError{
				field:  "Policy",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MsgCreatePolicyResponseMultiError(errors)
	}

	return nil
}

// MsgCreatePolicyResponseMultiError is an error wrapping multiple validation
// errors returned by MsgCreatePolicyResponse.ValidateAll() if the designated
// constraints aren't met.
type MsgCreatePolicyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MsgCreatePolicyResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MsgCreatePolicyResponseMultiError) AllErrors() []error { return m }

// MsgCreatePolicyResponseValidationError is the validation error returned by
// MsgCreatePolicyResponse.Validate if the designated constraints aren't met.
type MsgCreatePolicyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MsgCreatePolicyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MsgCreatePolicyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MsgCreatePolicyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MsgCreatePolicyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MsgCreatePolicyResponseValidationError) ErrorName() string {
	return "MsgCreatePolicyResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MsgCreatePolicyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMsgCreatePolicyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MsgCreatePolicyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MsgCreatePolicyResponseValidationError{}

// Validate checks the field values on MsgSetRelationship with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MsgSetRelationship) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MsgSetRelationship with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MsgSetRelationshipMultiError, or nil if none found.
func (m *MsgSetRelationship) ValidateAll() error {
	return m.validate(true)
}

func (m *MsgSetRelationship) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Creator

	// no validation rules for PolicyId

	if all {
		switch v := interface{}(m.GetCreationTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MsgSetRelationshipValidationError{
					field:  "CreationTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MsgSetRelationshipValidationError{
					field:  "CreationTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreationTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MsgSetRelationshipValidationError{
				field:  "CreationTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetRelationship()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MsgSetRelationshipValidationError{
					field:  "Relationship",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MsgSetRelationshipValidationError{
					field:  "Relationship",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRelationship()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MsgSetRelationshipValidationError{
				field:  "Relationship",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MsgSetRelationshipMultiError(errors)
	}

	return nil
}

// MsgSetRelationshipMultiError is an error wrapping multiple validation errors
// returned by MsgSetRelationship.ValidateAll() if the designated constraints
// aren't met.
type MsgSetRelationshipMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MsgSetRelationshipMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MsgSetRelationshipMultiError) AllErrors() []error { return m }

// MsgSetRelationshipValidationError is the validation error returned by
// MsgSetRelationship.Validate if the designated constraints aren't met.
type MsgSetRelationshipValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MsgSetRelationshipValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MsgSetRelationshipValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MsgSetRelationshipValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MsgSetRelationshipValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MsgSetRelationshipValidationError) ErrorName() string {
	return "MsgSetRelationshipValidationError"
}

// Error satisfies the builtin error interface
func (e MsgSetRelationshipValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMsgSetRelationship.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MsgSetRelationshipValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MsgSetRelationshipValidationError{}

// Validate checks the field values on MsgSetRelationshipResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MsgSetRelationshipResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MsgSetRelationshipResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MsgSetRelationshipResponseMultiError, or nil if none found.
func (m *MsgSetRelationshipResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MsgSetRelationshipResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RecordUpdated

	if len(errors) > 0 {
		return MsgSetRelationshipResponseMultiError(errors)
	}

	return nil
}

// MsgSetRelationshipResponseMultiError is an error wrapping multiple
// validation errors returned by MsgSetRelationshipResponse.ValidateAll() if
// the designated constraints aren't met.
type MsgSetRelationshipResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MsgSetRelationshipResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MsgSetRelationshipResponseMultiError) AllErrors() []error { return m }

// MsgSetRelationshipResponseValidationError is the validation error returned
// by MsgSetRelationshipResponse.Validate if the designated constraints aren't met.
type MsgSetRelationshipResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MsgSetRelationshipResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MsgSetRelationshipResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MsgSetRelationshipResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MsgSetRelationshipResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MsgSetRelationshipResponseValidationError) ErrorName() string {
	return "MsgSetRelationshipResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MsgSetRelationshipResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMsgSetRelationshipResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MsgSetRelationshipResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MsgSetRelationshipResponseValidationError{}

// Validate checks the field values on MsgDeleteRelationship with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MsgDeleteRelationship) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MsgDeleteRelationship with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MsgDeleteRelationshipMultiError, or nil if none found.
func (m *MsgDeleteRelationship) ValidateAll() error {
	return m.validate(true)
}

func (m *MsgDeleteRelationship) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Creator

	// no validation rules for PolicyId

	if all {
		switch v := interface{}(m.GetObject()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MsgDeleteRelationshipValidationError{
					field:  "Object",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MsgDeleteRelationshipValidationError{
					field:  "Object",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetObject()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MsgDeleteRelationshipValidationError{
				field:  "Object",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Relation

	if all {
		switch v := interface{}(m.GetSubject()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MsgDeleteRelationshipValidationError{
					field:  "Subject",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MsgDeleteRelationshipValidationError{
					field:  "Subject",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSubject()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MsgDeleteRelationshipValidationError{
				field:  "Subject",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MsgDeleteRelationshipMultiError(errors)
	}

	return nil
}

// MsgDeleteRelationshipMultiError is an error wrapping multiple validation
// errors returned by MsgDeleteRelationship.ValidateAll() if the designated
// constraints aren't met.
type MsgDeleteRelationshipMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MsgDeleteRelationshipMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MsgDeleteRelationshipMultiError) AllErrors() []error { return m }

// MsgDeleteRelationshipValidationError is the validation error returned by
// MsgDeleteRelationship.Validate if the designated constraints aren't met.
type MsgDeleteRelationshipValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MsgDeleteRelationshipValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MsgDeleteRelationshipValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MsgDeleteRelationshipValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MsgDeleteRelationshipValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MsgDeleteRelationshipValidationError) ErrorName() string {
	return "MsgDeleteRelationshipValidationError"
}

// Error satisfies the builtin error interface
func (e MsgDeleteRelationshipValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMsgDeleteRelationship.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MsgDeleteRelationshipValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MsgDeleteRelationshipValidationError{}

// Validate checks the field values on MsgDeleteRelationshipResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MsgDeleteRelationshipResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MsgDeleteRelationshipResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// MsgDeleteRelationshipResponseMultiError, or nil if none found.
func (m *MsgDeleteRelationshipResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MsgDeleteRelationshipResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RecordFound

	if len(errors) > 0 {
		return MsgDeleteRelationshipResponseMultiError(errors)
	}

	return nil
}

// MsgDeleteRelationshipResponseMultiError is an error wrapping multiple
// validation errors returned by MsgDeleteRelationshipResponse.ValidateAll()
// if the designated constraints aren't met.
type MsgDeleteRelationshipResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MsgDeleteRelationshipResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MsgDeleteRelationshipResponseMultiError) AllErrors() []error { return m }

// MsgDeleteRelationshipResponseValidationError is the validation error
// returned by MsgDeleteRelationshipResponse.Validate if the designated
// constraints aren't met.
type MsgDeleteRelationshipResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MsgDeleteRelationshipResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MsgDeleteRelationshipResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MsgDeleteRelationshipResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MsgDeleteRelationshipResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MsgDeleteRelationshipResponseValidationError) ErrorName() string {
	return "MsgDeleteRelationshipResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MsgDeleteRelationshipResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMsgDeleteRelationshipResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MsgDeleteRelationshipResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MsgDeleteRelationshipResponseValidationError{}

// Validate checks the field values on MsgRegisterObject with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *MsgRegisterObject) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MsgRegisterObject with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MsgRegisterObjectMultiError, or nil if none found.
func (m *MsgRegisterObject) ValidateAll() error {
	return m.validate(true)
}

func (m *MsgRegisterObject) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Creator

	// no validation rules for PolicyId

	if all {
		switch v := interface{}(m.GetRegistration()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MsgRegisterObjectValidationError{
					field:  "Registration",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MsgRegisterObjectValidationError{
					field:  "Registration",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegistration()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MsgRegisterObjectValidationError{
				field:  "Registration",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreationTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MsgRegisterObjectValidationError{
					field:  "CreationTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MsgRegisterObjectValidationError{
					field:  "CreationTime",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreationTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MsgRegisterObjectValidationError{
				field:  "CreationTime",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MsgRegisterObjectMultiError(errors)
	}

	return nil
}

// MsgRegisterObjectMultiError is an error wrapping multiple validation errors
// returned by MsgRegisterObject.ValidateAll() if the designated constraints
// aren't met.
type MsgRegisterObjectMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MsgRegisterObjectMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MsgRegisterObjectMultiError) AllErrors() []error { return m }

// MsgRegisterObjectValidationError is the validation error returned by
// MsgRegisterObject.Validate if the designated constraints aren't met.
type MsgRegisterObjectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MsgRegisterObjectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MsgRegisterObjectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MsgRegisterObjectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MsgRegisterObjectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MsgRegisterObjectValidationError) ErrorName() string {
	return "MsgRegisterObjectValidationError"
}

// Error satisfies the builtin error interface
func (e MsgRegisterObjectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMsgRegisterObject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MsgRegisterObjectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MsgRegisterObjectValidationError{}

// Validate checks the field values on MsgRegisterObjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MsgRegisterObjectResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MsgRegisterObjectResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MsgRegisterObjectResponseMultiError, or nil if none found.
func (m *MsgRegisterObjectResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MsgRegisterObjectResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Result

	if len(errors) > 0 {
		return MsgRegisterObjectResponseMultiError(errors)
	}

	return nil
}

// MsgRegisterObjectResponseMultiError is an error wrapping multiple validation
// errors returned by MsgRegisterObjectResponse.ValidateAll() if the
// designated constraints aren't met.
type MsgRegisterObjectResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MsgRegisterObjectResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MsgRegisterObjectResponseMultiError) AllErrors() []error { return m }

// MsgRegisterObjectResponseValidationError is the validation error returned by
// MsgRegisterObjectResponse.Validate if the designated constraints aren't met.
type MsgRegisterObjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MsgRegisterObjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MsgRegisterObjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MsgRegisterObjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MsgRegisterObjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MsgRegisterObjectResponseValidationError) ErrorName() string {
	return "MsgRegisterObjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MsgRegisterObjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMsgRegisterObjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MsgRegisterObjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MsgRegisterObjectResponseValidationError{}

// Validate checks the field values on MsgUnregisterObject with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MsgUnregisterObject) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MsgUnregisterObject with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MsgUnregisterObjectMultiError, or nil if none found.
func (m *MsgUnregisterObject) ValidateAll() error {
	return m.validate(true)
}

func (m *MsgUnregisterObject) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Creator

	// no validation rules for PolicyId

	if all {
		switch v := interface{}(m.GetObject()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, MsgUnregisterObjectValidationError{
					field:  "Object",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, MsgUnregisterObjectValidationError{
					field:  "Object",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetObject()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return MsgUnregisterObjectValidationError{
				field:  "Object",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return MsgUnregisterObjectMultiError(errors)
	}

	return nil
}

// MsgUnregisterObjectMultiError is an error wrapping multiple validation
// errors returned by MsgUnregisterObject.ValidateAll() if the designated
// constraints aren't met.
type MsgUnregisterObjectMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MsgUnregisterObjectMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MsgUnregisterObjectMultiError) AllErrors() []error { return m }

// MsgUnregisterObjectValidationError is the validation error returned by
// MsgUnregisterObject.Validate if the designated constraints aren't met.
type MsgUnregisterObjectValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MsgUnregisterObjectValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MsgUnregisterObjectValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MsgUnregisterObjectValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MsgUnregisterObjectValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MsgUnregisterObjectValidationError) ErrorName() string {
	return "MsgUnregisterObjectValidationError"
}

// Error satisfies the builtin error interface
func (e MsgUnregisterObjectValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMsgUnregisterObject.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MsgUnregisterObjectValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MsgUnregisterObjectValidationError{}

// Validate checks the field values on MsgUnregisterObjectResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *MsgUnregisterObjectResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MsgUnregisterObjectResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// MsgUnregisterObjectResponseMultiError, or nil if none found.
func (m *MsgUnregisterObjectResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *MsgUnregisterObjectResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Found

	if len(errors) > 0 {
		return MsgUnregisterObjectResponseMultiError(errors)
	}

	return nil
}

// MsgUnregisterObjectResponseMultiError is an error wrapping multiple
// validation errors returned by MsgUnregisterObjectResponse.ValidateAll() if
// the designated constraints aren't met.
type MsgUnregisterObjectResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MsgUnregisterObjectResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MsgUnregisterObjectResponseMultiError) AllErrors() []error { return m }

// MsgUnregisterObjectResponseValidationError is the validation error returned
// by MsgUnregisterObjectResponse.Validate if the designated constraints
// aren't met.
type MsgUnregisterObjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MsgUnregisterObjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MsgUnregisterObjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MsgUnregisterObjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MsgUnregisterObjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MsgUnregisterObjectResponseValidationError) ErrorName() string {
	return "MsgUnregisterObjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e MsgUnregisterObjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMsgUnregisterObjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MsgUnregisterObjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MsgUnregisterObjectResponseValidationError{}
